#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.999e80544755ecac2e2b01d06682b4262a4d5b81.name = "old version"