#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_check_error	# Active trap pour arrêter le script si une erreur est détectée.

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
admin_name=$YNH_APP_ARG_ADMIN_NAME
admin_pass=$YNH_APP_ARG_ADMIN_PASS
admin_email=$YNH_APP_ARG_ADMIN_EMAIL
website_title=$YNH_APP_ARG_WEBSITE_TITLE
language=$YNH_APP_ARG_LANGUAGE


app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

CHECK_USER "$admin_name"	# Vérifie la validité de l'user admin
path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

user="$app"
ynh_app_setting_set "$app" is_public "$is_public"
ynh_app_setting_set "$app" admin_pass "$admin_pass"
ynh_app_setting_set "$app" admin_name "$admin_name"
ynh_app_setting_set "$app" admin_email "$admin_email"
ynh_app_setting_set "$app" language "$language"
ynh_app_setting_set "$app" website_title "$website_title"

#=================================================
# Check password strength
#=================================================

[[ ${#admin_pass} -gt 5 ]] || ynh_die \
"The password is too weak, it must be longer than 5 characters"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# CREATE A SQL BDD
#=================================================

db_name=$app
db_user=$app
db_pass=$(ynh_string_random)
ynh_mysql_create_db "$db_name" "$db_user" "$db_pass"
ynh_app_setting_set "$app" db_name "$db_name"
ynh_app_setting_set "$app" db_pass "$db_pass"
ynh_app_setting_set "$app" db_user "$db_user"
ynh_app_setting_set "$app" mysqlpwd "$db_pass"
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

final_path=/var/www/$app
ynh_app_setting_set $app final_path $final_path
SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

POOL_FPM

#=================================================
# SPECIFIC SETUP
#=================================================
# LANGUAGE
#=================================================
if [ $language = "En" ]
then
    language=en_GB
elif [ $language = "Fr" ] 
then
    language=fr_FR
elif [ $language = "De" ] 
then
    language=de_DE
elif [ $language = "Pt" ] 
then
    language=pt_PT
else 
    ynh_die "Language is no available"
fi


#================================================
# Installation : Get Composer:
#=================================================
echo "The installation can take long. So be patient ! :)"
pushd $final_path
sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
sudo php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php composer-setup.php
sudo php -r "unlink('composer-setup.php');"
sudo ./composer.phar install
sudo ./concrete/bin/concrete5 c5:install --db-server=localhost \
                                         --db-username=$db_user \
                                         --db-password=$db_pass \
                                         --db-database=$db_name \
                                         --site="'$website_title'" \
                                         --admin-email="'$admin_email'" \
                                         --admin-password=$admin_pass \
                                         --language=$language
popd

#=================================================
# Set permissions
#=================================================

sudo chown www-data:www-data $final_path -R
sudo chmod 777 $final_path -R


#=================================================
# NGINX CONFIGURATION
#=================================================

nginxconf="../conf/nginx.conf"
# Copy and set nginx configuration
sed -i "s@{PATH}@${path_url}@g"        $nginxconf
sed -i "s@{LOCATION}@${path_url:-/}@g" $nginxconf
sed -i "s@{DESTDIR}@${final_path}@g"  $nginxconf
sed -i "s@{POOLNAME}@${app}@g"     $nginxconf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/${domain}.d/${app}.conf

#=================================================
# SETUP SSOWAT
#=================================================

# Make app private if necessary
ynh_app_setting_set "$app" is_public "$is_public"
if [ "$is_public" = "Yes" ];
then
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

#=================================================
# RELOAD NGINX
#=================================================

sudo service nginx reload
