#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


admin_email=$(ynh_user_get_info --username="$admin" --key="mail")
ynh_app_setting_set --key=admin_email --value="$admin_email"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# INSTALL COMPOSER
#=================================================
ynh_script_progression "Installing Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev

#================================================
# CONCRETE5 INSTALLATION
#=================================================
ynh_script_progression "Concrete5 Installation, the installation can take long. So be patient ! :)"

ynh_mysql_db_shell <<< "ALTER DATABASE $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

pushd "$install_dir"
    ./concrete/bin/concrete5 c5:install --db-server=localhost \
        --db-username="$db_user" \
        --db-database="$db_name" \
        --db-password="$db_pwd" \
        --site="$website_title" \
        --admin-email="$admin_email" \
        --admin-password="$password" \
        --language="$language" \
        --site-locale="$language" \
        --verbose \
        --no-interaction \
        --allow-as-root
popd

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
